# Generated by Django 5.1.6 on 2025-04-01 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobiles', '0008_alter_mobiles_ean'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=255, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.mobiles')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('author', 'phone'), name='1_author_per_phone_model', violation_error_message='Author already added this phone!')],
            },
        ),
    ]
