# Generated by Django 5.1.6 on 2025-04-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_marketer',
            field=models.BooleanField(default=False, help_text="Designates whether the user's type is marketer."),
        ),
    ]
