# Generated by Django 5.1.6 on 2025-02-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
