# Generated by Django 5.1.6 on 2025-02-18 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0002_alter_mobiles_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mobiles',
        ),
    ]
