# Generated by Django 5.1.6 on 2025-02-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mobiles',
        ),
    ]
