# Generated by Django 5.1.6 on 2025-02-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobiles', '0005_delete_mobiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('ean', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
