# Generated by Django 5.1.6 on 2025-02-18 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0007_alter_mobiles_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='ean',
            field=models.CharField(help_text='Enter a 13-digit EAN (only numbers).', max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='EAN must be exactly 13 digits.', regex='^\\d{13}$')]),
        ),
    ]
